### ISSUE TITLE
Implement testing patterns 

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#33]
My biggest fear in proposing changes is unknowingly breaking something else. It’s less of an issue for devs who have a deep understanding of the code base, but I’m not there yet. 

My forte is java and I feel very comfortable over there with the build tools and unit testing. I have started a java port of the project. I have gotten pretty far but I also don’t mind learning c++. 

So I have started looking into unit testing. I found a few libraries that seems popular

-  [Boost.Test](https://www.boost.org/doc/libs/1_82_0/libs/test/doc/html/index.html)
- [Catch2](https://github.com/catchorg/Catch2)
- [ut](https://github.com/boost-ext/ut)
- [Google Test](https://github.com/google/googletest)
- [doctest](https://github.com/doctest/doctest)
- CMakes built in [CTest](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html) 

do you have any opinions on unit testing? Any experience with these unit testing libs? What are your thoughts?

edit: this might be a good overview for me https://www.jetbrains.com/help/clion/unit-testing-tutorial.html

**Comment by pappde** [comment]
Certainly a good idea to have, particularly for parsing and rules. No preference, other than something easy to maintain. I suspect some of these may have a bit more overhead to integrate. For example, the project doesn't use Boost, so using Boost.Test may not be ideal.

**Comment by danlangford** [comment]
I have something working on my machine with Google Test. chosen strictly due to good IDE support (CLion, VisualStudio). I'll get a PR over sometime to show you

**Comment by danlangford** [comment]
closed by #34
