### ISSUE TITLE
Cleanup file structure

### ISSUE THREAD

**Issue by pappde** [pappde/bmai#44]
One issue with the file structure is inconsistency between classes and headers.  E.g.
1. we have "parser.h" for the BMC_Parser class, but the implementation is in bmail.cpp (should be parser.cpp)
2. "bmai.h" (and bmai.cpp) are mega-files that include multiple classes and definitions
3. arguably, the files should exactly match the class name. E.g. "BMC_Parser.h" instead of "parser.h"
4. header dependencies are not consistent

REQUIREMENTS
Ideally, we would have one header and CPP per class.  

NOTES:
Cleaning up the headers should be straightforward - such as splitting bmai.h into multiple headers (actually added types.h in commit 94ed97d). What is a bit more involved is cleaning up bmai.cpp. For example, there are many dependencies on global/singleton objects declared in bmai.cpp, so we would need to extern them in the header file.

**Comment by danlangford** [comment]
FYI I'm taking stab at this now
