### ISSUE TITLE
Rev copyright to 2025

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#70]
I’m planning on finishing #69 soon and I propose we stamp v3.1 and we should have the 2025 copyright is a part of v3.1

I’m planning on doing this.

**Comment by danlangford** [comment]
actually there are a lot of compelling reasons why you should NOT have a year range
https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#why-not-bump-the-year-on-change

**Comment by pappde** [comment]
Interesting - seems to be over-complicating what is traditionally a simple process of having a simple template in your files. I can appreciate the subtleties matter in bigger and more complex OpenSource projects (or perhaps as software gets away from "files").

**Comment by danlangford** [comment]
after some research I put together 1 approach in #71. 
it leans on the REUSE and SPDX specifications and patterns
it automates checking that we have specified a copyright and license for each file
it helps us comply with license requirements

im not married to it though. if you don't like it im ok if you junk it.
